---
- name: Ansible SSM Test
  hosts: all
  vars:
      ansible_connection: aws_ssm
      ansible_aws_ssm_bucket_name: s3ansiblessm-2024
      ansible_aws_ssm_region: us-east-2
      ansible_python_interpreter: auto_silent

  tasks:
  
  - name: Example from an Ansible Playbook
    ansible.builtin.ping: