---
- name: Ansible SSM Test
  hosts: all
  gather_facts: false
  vars:
      ansible_connection: aws_ssm
      ansible_aws_ssm_bucket_name: ansible-deploy-bucket
      ansible_aws_ssm_region: us-east-1
      ansible_python_interpreter: auto_silent

  tasks:
  
  - name: Test connectivity
    ansible.builtin.ping:

  - name: Install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
    become: true