name: Testing Deployer
on: [push]

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ROLE_TO_ASSUME: ${{ vars.ROLE_TO_ASSUME }}
  ROLE_SESSION_NAME: ${{ vars.ROLE_SESSION_NAME }}

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  Ansible-Test-Job:
    runs-on: codebuild-lab-gh-1-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: "Install Ansible packages"
        shell: bash
        run: |
             apt update
             apt install software-properties-common
             add-apt-repository --yes --update ppa:ansible/ansible
             apt install ansible python-boto3 --yes
 
      - name: Ansible Test 1
        run: ansible-inventory -i aws_ec2.yaml --list
        working-directory: ansible

     

      

