name: Hello World
on: [push]

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ROLE_TO_ASSUME: ${{ vars.ROLE_TO_ASSUME }}
  ROLE_SESSION_NAME: ${{ vars.ROLE_SESSION_NAME }}

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  Hello-World-Job:
    runs-on: codebuild-TEST-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Copy files to the test website with the AWS CLI
        run: |
            aws s3 ls

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@VERSION 
        with:
              version: "9.3.0"
    
      - name: "Print Ansible version"
        run: ansible-playbook --version
